#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.
IMAGE_REPO=${IMAGE_NAME%:*}
IMAGE_TAG=${IMAGE_NAME#*:}

if [ $IMAGE_TAG = "nospark" ]; then
    DOCKER_FILE="Dockerfile_NoSpark"
else
    DOCKER_FILE="Dockerfile"
fi

# Trigger build
docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             -f $DOCKER_FILE \
             -t $IMAGE_NAME .