#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.
IMAGE_REPO=${IMAGE_NAME%:*}
IMAGE_TAG=${IMAGE_NAME#*:}

JH_VERSION=${IMAGE_TAG%-*}
SPARK_VERSION=${IMAGE_TAG#*-}

if [ $SPARK_VERSION = "nospark" ]; then
    DOCKER_FILE="Dockerfile_NoSpark"
else
    DOCKER_FILE="Dockerfile"
fi

# Trigger build
docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg JH_VERSION=$JH_VERSION \
             -f $DOCKER_FILE \
             -t $DOCKER_REPO:${DOCKER_TAG//,/ -t $DOCKER_REPO:} .
